// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.31.1
// source: schema/weather_seed.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "mariner.v1";

/**
 * WeatherSeed is the compressed regional payload sent to the boat.
 * Target size: < 5MB (compressed)
 */
export interface WeatherSeed {
  /** Identity */
  seedId: string;
  /** e.g., "ecmwf_aifs", "ecmwf_hres" */
  modelSource: string;
  /** ISO8601 timestamp of model initialization (e.g. 2026-01-18T00:00:00Z) */
  modelRunIso: string;
  createdAtIso: string;
  /** Spatial Domain */
  boundingBox:
    | BoundingBox
    | undefined;
  /** e.g., 0.25 */
  resolutionDeg: number;
  /** Temporal Domain */
  forecastStartIso: string;
  forecastEndIso: string;
  timeStepHours: number;
  timeStepsIso: string[];
  /**
   * Data
   * Coordinate arrays are stored once to save space
   */
  latitudes: number[];
  longitudes: number[];
  /**
   * Variable Data
   * Map of variable name (e.g., "u10", "msl") to its data payload
   * We use a list of NamedVariable because map<string, VariableData> isn't always efficient/supported everywhere
   */
  variables: NamedVariable[];
  /** Metadata */
  metaTags: { [key: string]: string };
}

export interface WeatherSeed_MetaTagsEntry {
  key: string;
  value: string;
}

export interface BoundingBox {
  latMin: number;
  latMax: number;
  lonMin: number;
  lonMax: number;
}

export interface NamedVariable {
  name: string;
  data: VariableData | undefined;
}

/**
 * Shape: [time, lat, lon] flattened
 * For maximum compression, we use packed floats or bytes (if quantized)
 */
export interface VariableData {
  /** Standard float32 array (Legacy/High Precision) */
  values: number[];
  /**
   * Quantized integers (Preferred for satellite)
   * Encoded as: original = offset + (quantized * scale)
   */
  quantizedValues: number[];
  scaleFactor: number;
  addOffset: number;
}

function createBaseWeatherSeed(): WeatherSeed {
  return {
    seedId: "",
    modelSource: "",
    modelRunIso: "",
    createdAtIso: "",
    boundingBox: undefined,
    resolutionDeg: 0,
    forecastStartIso: "",
    forecastEndIso: "",
    timeStepHours: 0,
    timeStepsIso: [],
    latitudes: [],
    longitudes: [],
    variables: [],
    metaTags: {},
  };
}

export const WeatherSeed: MessageFns<WeatherSeed> = {
  encode(message: WeatherSeed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seedId !== "") {
      writer.uint32(10).string(message.seedId);
    }
    if (message.modelSource !== "") {
      writer.uint32(18).string(message.modelSource);
    }
    if (message.modelRunIso !== "") {
      writer.uint32(26).string(message.modelRunIso);
    }
    if (message.createdAtIso !== "") {
      writer.uint32(34).string(message.createdAtIso);
    }
    if (message.boundingBox !== undefined) {
      BoundingBox.encode(message.boundingBox, writer.uint32(42).fork()).join();
    }
    if (message.resolutionDeg !== 0) {
      writer.uint32(53).float(message.resolutionDeg);
    }
    if (message.forecastStartIso !== "") {
      writer.uint32(58).string(message.forecastStartIso);
    }
    if (message.forecastEndIso !== "") {
      writer.uint32(66).string(message.forecastEndIso);
    }
    if (message.timeStepHours !== 0) {
      writer.uint32(72).int32(message.timeStepHours);
    }
    for (const v of message.timeStepsIso) {
      writer.uint32(82).string(v!);
    }
    writer.uint32(90).fork();
    for (const v of message.latitudes) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(98).fork();
    for (const v of message.longitudes) {
      writer.float(v);
    }
    writer.join();
    for (const v of message.variables) {
      NamedVariable.encode(v!, writer.uint32(106).fork()).join();
    }
    globalThis.Object.entries(message.metaTags).forEach(([key, value]: [string, string]) => {
      WeatherSeed_MetaTagsEntry.encode({ key: key as any, value }, writer.uint32(114).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WeatherSeed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWeatherSeed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.seedId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modelSource = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.modelRunIso = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAtIso = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.boundingBox = BoundingBox.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.resolutionDeg = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.forecastStartIso = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.forecastEndIso = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.timeStepHours = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.timeStepsIso.push(reader.string());
          continue;
        }
        case 11: {
          if (tag === 93) {
            message.latitudes.push(reader.float());

            continue;
          }

          if (tag === 90) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.latitudes.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 12: {
          if (tag === 101) {
            message.longitudes.push(reader.float());

            continue;
          }

          if (tag === 98) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.longitudes.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.variables.push(NamedVariable.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          const entry14 = WeatherSeed_MetaTagsEntry.decode(reader, reader.uint32());
          if (entry14.value !== undefined) {
            message.metaTags[entry14.key] = entry14.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<WeatherSeed>, I>>(base?: I): WeatherSeed {
    return WeatherSeed.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WeatherSeed>, I>>(object: I): WeatherSeed {
    const message = createBaseWeatherSeed();
    message.seedId = object.seedId ?? "";
    message.modelSource = object.modelSource ?? "";
    message.modelRunIso = object.modelRunIso ?? "";
    message.createdAtIso = object.createdAtIso ?? "";
    message.boundingBox = (object.boundingBox !== undefined && object.boundingBox !== null)
      ? BoundingBox.fromPartial(object.boundingBox)
      : undefined;
    message.resolutionDeg = object.resolutionDeg ?? 0;
    message.forecastStartIso = object.forecastStartIso ?? "";
    message.forecastEndIso = object.forecastEndIso ?? "";
    message.timeStepHours = object.timeStepHours ?? 0;
    message.timeStepsIso = object.timeStepsIso?.map((e) => e) || [];
    message.latitudes = object.latitudes?.map((e) => e) || [];
    message.longitudes = object.longitudes?.map((e) => e) || [];
    message.variables = object.variables?.map((e) => NamedVariable.fromPartial(e)) || [];
    message.metaTags = (globalThis.Object.entries(object.metaTags ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseWeatherSeed_MetaTagsEntry(): WeatherSeed_MetaTagsEntry {
  return { key: "", value: "" };
}

export const WeatherSeed_MetaTagsEntry: MessageFns<WeatherSeed_MetaTagsEntry> = {
  encode(message: WeatherSeed_MetaTagsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WeatherSeed_MetaTagsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWeatherSeed_MetaTagsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<WeatherSeed_MetaTagsEntry>, I>>(base?: I): WeatherSeed_MetaTagsEntry {
    return WeatherSeed_MetaTagsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WeatherSeed_MetaTagsEntry>, I>>(object: I): WeatherSeed_MetaTagsEntry {
    const message = createBaseWeatherSeed_MetaTagsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseBoundingBox(): BoundingBox {
  return { latMin: 0, latMax: 0, lonMin: 0, lonMax: 0 };
}

export const BoundingBox: MessageFns<BoundingBox> = {
  encode(message: BoundingBox, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.latMin !== 0) {
      writer.uint32(13).float(message.latMin);
    }
    if (message.latMax !== 0) {
      writer.uint32(21).float(message.latMax);
    }
    if (message.lonMin !== 0) {
      writer.uint32(29).float(message.lonMin);
    }
    if (message.lonMax !== 0) {
      writer.uint32(37).float(message.lonMax);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BoundingBox {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBoundingBox();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.latMin = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.latMax = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.lonMin = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.lonMax = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<BoundingBox>, I>>(base?: I): BoundingBox {
    return BoundingBox.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BoundingBox>, I>>(object: I): BoundingBox {
    const message = createBaseBoundingBox();
    message.latMin = object.latMin ?? 0;
    message.latMax = object.latMax ?? 0;
    message.lonMin = object.lonMin ?? 0;
    message.lonMax = object.lonMax ?? 0;
    return message;
  },
};

function createBaseNamedVariable(): NamedVariable {
  return { name: "", data: undefined };
}

export const NamedVariable: MessageFns<NamedVariable> = {
  encode(message: NamedVariable, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.data !== undefined) {
      VariableData.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NamedVariable {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNamedVariable();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = VariableData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<NamedVariable>, I>>(base?: I): NamedVariable {
    return NamedVariable.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamedVariable>, I>>(object: I): NamedVariable {
    const message = createBaseNamedVariable();
    message.name = object.name ?? "";
    message.data = (object.data !== undefined && object.data !== null)
      ? VariableData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseVariableData(): VariableData {
  return { values: [], quantizedValues: [], scaleFactor: 0, addOffset: 0 };
}

export const VariableData: MessageFns<VariableData> = {
  encode(message: VariableData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.values) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(18).fork();
    for (const v of message.quantizedValues) {
      writer.int32(v);
    }
    writer.join();
    if (message.scaleFactor !== 0) {
      writer.uint32(29).float(message.scaleFactor);
    }
    if (message.addOffset !== 0) {
      writer.uint32(37).float(message.addOffset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VariableData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariableData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.values.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.values.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag === 16) {
            message.quantizedValues.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.quantizedValues.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.scaleFactor = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.addOffset = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<VariableData>, I>>(base?: I): VariableData {
    return VariableData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VariableData>, I>>(object: I): VariableData {
    const message = createBaseVariableData();
    message.values = object.values?.map((e) => e) || [];
    message.quantizedValues = object.quantizedValues?.map((e) => e) || [];
    message.scaleFactor = object.scaleFactor ?? 0;
    message.addOffset = object.addOffset ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
