"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class WeatherSeed(_message.Message):
    """WeatherSeed is the compressed regional payload sent to the boat.
    Target size: < 5MB (compressed)
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetaTagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SEED_ID_FIELD_NUMBER: _builtins.int
    MODEL_SOURCE_FIELD_NUMBER: _builtins.int
    MODEL_RUN_ISO_FIELD_NUMBER: _builtins.int
    CREATED_AT_ISO_FIELD_NUMBER: _builtins.int
    BOUNDING_BOX_FIELD_NUMBER: _builtins.int
    RESOLUTION_DEG_FIELD_NUMBER: _builtins.int
    FORECAST_START_ISO_FIELD_NUMBER: _builtins.int
    FORECAST_END_ISO_FIELD_NUMBER: _builtins.int
    TIME_STEP_HOURS_FIELD_NUMBER: _builtins.int
    TIME_STEPS_ISO_FIELD_NUMBER: _builtins.int
    LATITUDES_FIELD_NUMBER: _builtins.int
    LONGITUDES_FIELD_NUMBER: _builtins.int
    VARIABLES_FIELD_NUMBER: _builtins.int
    META_TAGS_FIELD_NUMBER: _builtins.int
    seed_id: _builtins.str
    """Identity"""
    model_source: _builtins.str
    """e.g., "ecmwf_aifs", "ecmwf_hres" """
    model_run_iso: _builtins.str
    """ISO8601 timestamp of model initialization (e.g. 2026-01-18T00:00:00Z)"""
    created_at_iso: _builtins.str
    resolution_deg: _builtins.float
    """e.g., 0.25"""
    forecast_start_iso: _builtins.str
    """Temporal Domain"""
    forecast_end_iso: _builtins.str
    time_step_hours: _builtins.int
    @_builtins.property
    def bounding_box(self) -> Global___BoundingBox:
        """Spatial Domain"""

    @_builtins.property
    def time_steps_iso(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def latitudes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Data
        Coordinate arrays are stored once to save space
        """

    @_builtins.property
    def longitudes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def variables(self) -> _containers.RepeatedCompositeFieldContainer[Global___NamedVariable]:
        """Variable Data
        Map of variable name (e.g., "u10", "msl") to its data payload
        We use a list of NamedVariable because map<string, VariableData> isn't always efficient/supported everywhere
        """

    @_builtins.property
    def meta_tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Metadata"""

    def __init__(
        self,
        *,
        seed_id: _builtins.str = ...,
        model_source: _builtins.str = ...,
        model_run_iso: _builtins.str = ...,
        created_at_iso: _builtins.str = ...,
        bounding_box: Global___BoundingBox | None = ...,
        resolution_deg: _builtins.float = ...,
        forecast_start_iso: _builtins.str = ...,
        forecast_end_iso: _builtins.str = ...,
        time_step_hours: _builtins.int = ...,
        time_steps_iso: _abc.Iterable[_builtins.str] | None = ...,
        latitudes: _abc.Iterable[_builtins.float] | None = ...,
        longitudes: _abc.Iterable[_builtins.float] | None = ...,
        variables: _abc.Iterable[Global___NamedVariable] | None = ...,
        meta_tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bounding_box", b"bounding_box"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bounding_box", b"bounding_box", "created_at_iso", b"created_at_iso", "forecast_end_iso", b"forecast_end_iso", "forecast_start_iso", b"forecast_start_iso", "latitudes", b"latitudes", "longitudes", b"longitudes", "meta_tags", b"meta_tags", "model_run_iso", b"model_run_iso", "model_source", b"model_source", "resolution_deg", b"resolution_deg", "seed_id", b"seed_id", "time_step_hours", b"time_step_hours", "time_steps_iso", b"time_steps_iso", "variables", b"variables"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WeatherSeed: _TypeAlias = WeatherSeed  # noqa: Y015

@_typing.final
class BoundingBox(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LAT_MIN_FIELD_NUMBER: _builtins.int
    LAT_MAX_FIELD_NUMBER: _builtins.int
    LON_MIN_FIELD_NUMBER: _builtins.int
    LON_MAX_FIELD_NUMBER: _builtins.int
    lat_min: _builtins.float
    lat_max: _builtins.float
    lon_min: _builtins.float
    lon_max: _builtins.float
    def __init__(
        self,
        *,
        lat_min: _builtins.float = ...,
        lat_max: _builtins.float = ...,
        lon_min: _builtins.float = ...,
        lon_max: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lat_max", b"lat_max", "lat_min", b"lat_min", "lon_max", b"lon_max", "lon_min", b"lon_min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BoundingBox: _TypeAlias = BoundingBox  # noqa: Y015

@_typing.final
class NamedVariable(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def data(self) -> Global___VariableData: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        data: Global___VariableData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NamedVariable: _TypeAlias = NamedVariable  # noqa: Y015

@_typing.final
class VariableData(_message.Message):
    """Shape: [time, lat, lon] flattened
    For maximum compression, we use packed floats or bytes (if quantized)
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    QUANTIZED_VALUES_FIELD_NUMBER: _builtins.int
    SCALE_FACTOR_FIELD_NUMBER: _builtins.int
    ADD_OFFSET_FIELD_NUMBER: _builtins.int
    scale_factor: _builtins.float
    add_offset: _builtins.float
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Standard float32 array (Legacy/High Precision)"""

    @_builtins.property
    def quantized_values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Quantized integers (Preferred for satellite)
        Encoded as: original = offset + (quantized * scale)
        """

    def __init__(
        self,
        *,
        values: _abc.Iterable[_builtins.float] | None = ...,
        quantized_values: _abc.Iterable[_builtins.int] | None = ...,
        scale_factor: _builtins.float = ...,
        add_offset: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["add_offset", b"add_offset", "quantized_values", b"quantized_values", "scale_factor", b"scale_factor", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VariableData: _TypeAlias = VariableData  # noqa: Y015
