# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/weather_seed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schema/weather_seed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19schema/weather_seed.proto\x12\nmariner.v1\"\xd1\x03\n\x0bWeatherSeed\x12\x0f\n\x07seed_id\x18\x01 \x01(\t\x12\x14\n\x0cmodel_source\x18\x02 \x01(\t\x12\x15\n\rmodel_run_iso\x18\x03 \x01(\t\x12\x16\n\x0e\x63reated_at_iso\x18\x04 \x01(\t\x12-\n\x0c\x62ounding_box\x18\x05 \x01(\x0b\x32\x17.mariner.v1.BoundingBox\x12\x16\n\x0eresolution_deg\x18\x06 \x01(\x02\x12\x1a\n\x12\x66orecast_start_iso\x18\x07 \x01(\t\x12\x18\n\x10\x66orecast_end_iso\x18\x08 \x01(\t\x12\x17\n\x0ftime_step_hours\x18\t \x01(\x05\x12\x16\n\x0etime_steps_iso\x18\n \x03(\t\x12\x11\n\tlatitudes\x18\x0b \x03(\x02\x12\x12\n\nlongitudes\x18\x0c \x03(\x02\x12,\n\tvariables\x18\r \x03(\x0b\x32\x19.mariner.v1.NamedVariable\x12\x38\n\tmeta_tags\x18\x0e \x03(\x0b\x32%.mariner.v1.WeatherSeed.MetaTagsEntry\x1a/\n\rMetaTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Q\n\x0b\x42oundingBox\x12\x0f\n\x07lat_min\x18\x01 \x01(\x02\x12\x0f\n\x07lat_max\x18\x02 \x01(\x02\x12\x0f\n\x07lon_min\x18\x03 \x01(\x02\x12\x0f\n\x07lon_max\x18\x04 \x01(\x02\"E\n\rNamedVariable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x18.mariner.v1.VariableData\"j\n\x0cVariableData\x12\x12\n\x06values\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x1c\n\x10quantized_values\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x14\n\x0cscale_factor\x18\x03 \x01(\x02\x12\x12\n\nadd_offset\x18\x04 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.weather_seed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEATHERSEED_METATAGSENTRY']._loaded_options = None
  _globals['_WEATHERSEED_METATAGSENTRY']._serialized_options = b'8\001'
  _globals['_VARIABLEDATA'].fields_by_name['values']._loaded_options = None
  _globals['_VARIABLEDATA'].fields_by_name['values']._serialized_options = b'\020\001'
  _globals['_VARIABLEDATA'].fields_by_name['quantized_values']._loaded_options = None
  _globals['_VARIABLEDATA'].fields_by_name['quantized_values']._serialized_options = b'\020\001'
  _globals['_WEATHERSEED']._serialized_start=42
  _globals['_WEATHERSEED']._serialized_end=507
  _globals['_WEATHERSEED_METATAGSENTRY']._serialized_start=460
  _globals['_WEATHERSEED_METATAGSENTRY']._serialized_end=507
  _globals['_BOUNDINGBOX']._serialized_start=509
  _globals['_BOUNDINGBOX']._serialized_end=590
  _globals['_NAMEDVARIABLE']._serialized_start=592
  _globals['_NAMEDVARIABLE']._serialized_end=661
  _globals['_VARIABLEDATA']._serialized_start=663
  _globals['_VARIABLEDATA']._serialized_end=769
# @@protoc_insertion_point(module_scope)
